{% set name = "py-pandoc" %}
{% set version = "2.9.2.1" %}
# {% set dep_ver = "2.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 805a8e36837b7c18c8c5cb01bf74ce5055ee2d90b6dd16259b2fda5522ec496a
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=20.0.2
  run:
    - python >=3.6
    - pandoc ={{ version }}

test:
  commands:
    - pandoc --version
    - pandoc --help

about:
  home: https://github.com/kiwi0fruit/py-pandoc
  license: GPLv2+
  license_family: GPL
  license_file: LICENSE
  summary: Installs pandoc conda package in pip and conda.
  doc_url: https://github.com/kiwi0fruit/py-pandoc
  dev_url: https://github.com/kiwi0fruit/py-pandoc

extra:
  recipe-maintainers:
    - kiwi0fruit
