{% set name = "py-pandoc" %}
{% set version = "2.6" %}
{% set pypi_build = ".0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}{{ pypi_build }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}{{ pypi_build }}.tar.gz
  sha256: b2d31457792d8a3b7c40850ef4f2ee1467f4658d44209da7869a5d0927b80f1b
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandoc ={{ version }}

test:
  commands:
    - pandoc --version
    - pandoc --help

about:
  home: https://github.com/kiwi0fruit/py-pandoc
  license: "GPLv2+"
  license_family: GPL
  license_file: LICENSE
  summary: "Pandoc in pip and conda."
  doc_url: https://github.com/kiwi0fruit/py-pandoc
  dev_url: https://github.com/kiwi0fruit/py-pandoc

extra:
  recipe-maintainers:
    - kiwi0fruit
