{% set name = "py-pandoc" %}
{% set version = "2.7.3" %}
{% set dep_ver = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17da695e15ea48f318d21b2091c65ae9cd1f297a490da23777eb2c639c50b341
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandoc ={{ dep_ver }}

test:
  commands:
    - pandoc --version
    - pandoc --help

about:
  home: https://github.com/kiwi0fruit/py-pandoc
  license: "GPLv2+"
  license_family: GPL
  license_file: LICENSE
  summary: "Installs pandoc conda package in pip and conda."
  doc_url: https://github.com/kiwi0fruit/py-pandoc
  dev_url: https://github.com/kiwi0fruit/py-pandoc

extra:
  recipe-maintainers:
    - kiwi0fruit
