{% set name = "py-pandoc" %}
{% set version = "2.9.2.0.1" %}
# {% set dep_ver = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa02a688d25ad2b212ccdbf12c43ccca3f79ad40433466e20083a4fd2f4785bf
  patches:
    - conda.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip >=20.0.2
  run:
    - python >=3.6
    - pandoc ={{ version }}

test:
  commands:
    - pandoc --version
    - pandoc --help

about:
  home: https://github.com/kiwi0fruit/py-pandoc
  license: "GPLv2+"
  license_family: GPL
  license_file: LICENSE
  summary: "Installs pandoc conda package in pip and conda."
  doc_url: https://github.com/kiwi0fruit/py-pandoc
  dev_url: https://github.com/kiwi0fruit/py-pandoc

extra:
  recipe-maintainers:
    - kiwi0fruit
